version: "3.8"

services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_DISCOVERY_URL=https://accounts.google.com/.well-known/openid-configuration
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - GOOGLE_DRIVE_KEY_PATH=${GOOGLE_DRIVE_KEY_PATH}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
    networks:
      - flask-network
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/flask-app.conf:/etc/nginx/conf.d/default.conf  # 위 설정 파일 마운트
      - /etc/letsencrypt:/etc/letsencrypt                      # 인증서 디렉토리 마운트
    depends_on:
      - flask-app
    networks:
      - flask-network
    restart: always

networks:
  flask-network:
    driver: bridge
